### ISSUE TITLE
Need to upgrade nested dependency log4j version in maven

### ISSUE THREAD

**Issue by Eric-git-999** [SPECCHIODB/SPECCHIO#8]
- log4j is a nested dependency with known vulnerabilities. The latest vulnerability does not imapct the current deployment of Specchio logv4 version 1.2.14 but this older version has known vulnerabilities, so needs to be updated to the latest version.
- it is present in .war for client and server:

SPECCHIO/src/client on  master via :coffee: v11.0.13 took 14s
❯ ../../gradlew -q dependencies  | grep log4j
|    \--- log4j:log4j:1.2.14
|    \--- log4j:log4j:1.2.14
|    \--- log4j:log4j:1.2.14
|    \--- log4j:log4j:1.2.14
|    \--- log4j:log4j:1.2.14
|    \--- log4j:log4j:1.2.14
|    \--- log4j:log4j:1.2.14
|    \--- log4j:log4j:1.2.14
|    \--- log4j:log4j:1.2.14

SPECCHIO/src/webapp on  master via :coffee: v11.0.13 
❯ ../../gradlew -q dependencies   | grep log4j
     |    +--- org.slf4j:log4j-over-slf4j:1.7.12
     |    \--- org.apache.tomcat.embed:tomcat-embed-logging-log4j:7.0.86
     |    \--- org.slf4j:log4j-over-slf4j:1.7.12
     |         \--- org.slf4j:log4j-over-slf4j:1.7.12
     |              \--- org.slf4j:log4j-over-slf4j:1.7.12

- current version of log4j should be used (2.16.0)

**Comment by ahueni** [comment]
That dependency in the client was due to the JXL jar. This has now been compiled locally, thereby allowing an upgrade to the latest log4j version.
Updating the webapp is currently not possible as we'd have to use org.gretty' version '4.0.0' and for that one would likely need Java 17, which is currently not possible due to an error in the gradle system. We need to revisit this later.
